config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "organizations#index"

  resources :organizations, only: [:index, :show]

  get 'users/new' => "users#new", as: :new_account
  post 'users' => 'users#create'

	get '/login'     => 'sessions#new'
	post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'  
  
  get '/search' => 'search#organizations'
  post '/search' => 'search#organizations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
    belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
  has_many :children, class_name: 'Organization', foreign_key: :parent_id
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :organizations, through: :memberships
  
  has_secure_password

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   # Make the current_user method available to views also, not just controllers:
   helper_method :current_user
  
   # Define the current_user method:
   def current_user
     # Look up the current user based on user_id in the session cookie:
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

   def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authorize
  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def organizations
        #pass variable :search from search bar
        if params[:search].blank?
            redirect_to root_path, alert: "Please enter a search term" 
        else
            #filter result to search name column and set column to lowecase before searching, match search to user's input
            @organizations = Organization.all.where("lower(name) LIKE ? ", "%#{params[:search]}").order('name')  
            @search_term = params[:search]
        end
    end

    def search_params
        params.permit(:search)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # No need for anything in here, we are just going to render our
    # new.html.erb AKA the login page
  end

  def create
    # Look up User in db by the email address submitted to the login form and
    # convert to lowercase to match email in db in case they had caps lock on:
    user = User.find_by(email: params[:login][:email].downcase)
    
    # Verify user exists in db and run has_secure_password's .authenticate() 
    # method to see if the password submitted on the login form was correct: 
    if user && user.authenticate(params[:login][:password]) 
      # Save the user.id in that user's session cookie:
      session[:user_id] = user.id.to_s
      redirect_to root_path, notice: 'Successfully logged in!'
    else
      # if email or password incorrect, re-render login page:
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
    # delete the saved user_id key/value from the cookie:
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    # store emails as lowercase to avoid duplicates and case-sensitive errors
    @user.email.downcase!

    if @user.save
      flash[:notice] = "Account created successfully."
      redirect_to root_path
    else
      flash.now.alert = "We couldn't create your account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <div class="top-nav">
          <div class="menu">
          <%= image_tag "listen360-logo.png", size: "24", :class => 'logo' %>
          <span class="company-details"> Listen360 - Alpharetta, GA</span>
          <span class="down-icon"><img src="https://img.icons8.com/material-rounded/24/000000/chevron-down.png"/></span>
          </div>
              <div class="search">
                <%= form_tag search_path, :method => 'post' do %>
                  <%= text_field_tag :search, params[:search], placeholder: "organization search", class: 'search-field' %>
                  <%= submit_tag "Search", name: nil, class: 'button' %> 
                <% end %>
              </div> 
              <div class="dropdown">
                <span class="user-info">
                    <% if current_user %>
                  <!-- current_user will return true if a user is logged in -->
                  
                      <%= "#{current_user.first_name} #{current_user.last_name}" %> <span class="down-icon"><img src="https://img.icons8.com/material-rounded/24/000000/chevron-down.png"/></span>
                      <span class="user-icon"><img src="https://img.icons8.com/material-sharp/24/000000/user-male-circle.png"/></i></span>
                      <div class="dropdown-content">
                        <%= link_to 'Home', root_path %>
                        <%= link_to 'Log Out', logout_path, method: :delete %>
                      </div>
                    <% else %>
                    <!-- not logged in -->
                      <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_account_path %>
                    <% end %>  
                  </span>  
               </div>    
          </div>
        </div>
      </nav>
    </header>
      <% if notice %>
        <%= notice %>
      <% end %>
      
      <% if alert %>
        <%= alert %>
      <% end %>
      <%= yield %>
  </body>
</html>

app/views/organizations/_organization.html.erb
<section class="org-container">
  <div class="org-header">
    <h1>
        <%= link_to(organization.name, organization_path(organization)) %>
    </h1>
     <hr>
  </div>
 
    <p class="org-details">
        <%= organization.description%>
    </p>
  </section>
 

app/views/organizations/index.html.erb
<% provide(:title, "All Organizations") %>

<%= render @organizations %>

app/views/organizations/show.html.erb
<div class="org-show">
<%= link_to("Back to All Organizations", organizations_path) %>
    <% provide(:title, @organization.name) %>
    <br>  
    <div class="org-header">
        <h1>  
            <%= @organization.name %>
        </h1>
    </div>
     <hr>
    <p class="org-details">
        <%= @organization.description %>
    </p>
</div>

app/views/search/organizations.html.erb
<p><%= link_to("Back to All Organizations", organizations_path) %></p>
<div class="search-results">
    <h2>Organizations Search Results</h2>
    <h3> <%= "Results for #{@search_term}" %>:</h3>
   
    <% @organizations.each do |org| %>
     <h4>
        <%= link_to(org.name, organization_path(org.id)) %>
        <hr>
    </h4>   
    <%end%>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, autofocus: true %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>